"""Public emergency endpoints — no authentication, fast, privacy-preserving.

A deleted or deactivated profile returns HTTP 410 with a generic message and
leaks nothing (no timing difference material, no data, no reason).
"""
import hashlib
from datetime import date, datetime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.core.config import Settings, get_settings
from app.core.database import get_db
from app.core.rate_limit import rate_limit
from app.models import MedicalProfile, ScanEvent
from app.schemas.profile import PublicProfileOut

router = APIRouter(prefix="/public", tags=["public"])

UNAVAILABLE = (
    "This CareCode profile is no longer available. "
    "The owner has deleted or deactivated this emergency profile."
)


def _resolve_public_profile(db: Session, code: str) -> MedicalProfile:
    profile = db.query(MedicalProfile).filter(MedicalProfile.carecode == code).first()
    if profile is None or profile.user is None or not profile.user.is_active:
        raise HTTPException(status.HTTP_410_GONE, UNAVAILABLE)
    return profile


def _age(birth: date | None) -> int | None:
    if birth is None:
        return None
    today = date.today()
    return today.year - birth.year - ((today.month, today.day) < (birth.month, birth.day))


def _to_public(profile: MedicalProfile) -> PublicProfileOut:
    return PublicProfileOut(
        carecode=profile.carecode,
        full_name=profile.full_name,
        age=_age(profile.date_of_birth),
        gender=profile.gender,
        blood_group=profile.blood_group,
        allergies=profile.allergies,
        conditions=profile.conditions,
        medications=profile.medications,
        address=profile.address,
        notes=profile.notes,
        photo_url=f"/api/v1/public/{profile.carecode}/photo" if profile.photo_filename else None,
        contacts=profile.contacts,
    )


@router.get("/{code}", response_model=PublicProfileOut)
def public_profile(
    code: str,
    request: Request,
    db: Session = Depends(get_db),
    settings: Settings = Depends(get_settings),
):
    profile = _resolve_public_profile(db, code)

    client_ip = request.client.host if request.client else "unknown"
    if not rate_limit(settings, f"scan:{code}", 30, 60):
        raise HTTPException(status.HTTP_429_TOO_MANY_REQUESTS, "Too many scans, try again shortly")

    # Privacy: store only a hash of the IP, never the raw address.
    ip_hash = hashlib.sha256(client_ip.encode("utf-8")).hexdigest()
    ua = (request.headers.get("user-agent") or "")[:255]

    db.add(ScanEvent(profile_id=profile.id, ip_hash=ip_hash, user_agent=ua or None))
    profile.scan_count += 1
    profile.last_scanned_at = datetime.now(timezone.utc)
    db.commit()

    return _to_public(profile)


@router.get("/{code}/photo")
def public_photo(
    code: str,
    db: Session = Depends(get_db),
    settings: Settings = Depends(get_settings),
):
    profile = _resolve_public_profile(db, code)
    if not profile.photo_filename:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "No photo")
    path = settings.storage_path / "photos" / profile.photo_filename
    if not path.is_file():
        raise HTTPException(status.HTTP_404_NOT_FOUND, "No photo")
    return FileResponse(path, media_type="image/jpeg")


@router.get("/{code}/summary")
def public_summary(
    code: str,
    db: Session = Depends(get_db),
    settings: Settings = Depends(get_settings),
):
    """Downloadable plain-text medical summary for responders."""
    profile = _resolve_public_profile(db, code)
    lines = [
        "CARECODE — EMERGENCY MEDICAL SUMMARY",
        "====================================",
        "",
        f"Name: {profile.full_name}",
        f"Date of birth: {profile.date_of_birth or 'Not provided'}",
        f"Age: {_age(profile.date_of_birth) if profile.date_of_birth else 'Unknown'}",
        f"Gender: {profile.gender or 'Not provided'}",
        f"Blood group: {profile.blood_group or 'Not provided'}",
        "",
        f"Allergies: {profile.allergies or 'None recorded'}",
        f"Medical conditions: {profile.conditions or 'None recorded'}",
        f"Current medications: {profile.medications or 'None recorded'}",
        f"Address: {profile.address or 'Not provided'}",
        f"Notes: {profile.notes or 'None'}",
        "",
        "EMERGENCY CONTACTS",
        "------------------",
    ]
    for c in profile.contacts:
        lines.append(f"- {c.name} ({c.relationship}): {c.phone}")
    if not profile.contacts:
        lines.append("- None recorded")
    lines += ["", "Generated by CareCode", str(datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))]

    return Response(
        content="\n".join(lines),
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="carecode-summary-{profile.carecode[:8]}.txt"'},
    )
